theme: jekyll-theme-cayman
title: Open Licensing and Creative Commons
description: This demonstration module was developed for the Creative Commons Certification for Educators course in Spring 2019 by <a href="mailto:addavis@olemiss.edu">Andrew Davis.</a>